import React, { createContext, useContext, useState, useEffect } from 'react';

const T = {
  en: {
    unitId: "Unique Unit ID",
    newHere: "New to MediLocker?",
    signUp: "Create your account →",
    signupLabel: "REGISTRATION",
    signupTitle: "Create your MediLocker.",
    signupText: "Enter your details once. A unique Unit ID will be generated for future sign-ins.",
    fullName: "Full name",
    phone: "Phone number",
    accountType: "Account type",
    dob: "Date of birth",
    gender: "Gender",
    address: "Address",
    city: "City",
    state: "State",
    pin: "PIN code",
    govid: "Government ID / Aadhaar",
    insurance: "Medical insurance",
    allergy: "Allergies, if any",
    extra: "Additional details",
    consent: "I confirm that the information provided is accurate and I understand that a unique Unit ID will be generated.",
    createAccount: "Create account & generate Unit ID ↗",
    ready: "Your account is ready.",
    saveUnit: "Save this Unit ID. You will need it with your registered email to sign in.",
    continueLogin: "Continue to login →",
    navFeatures: "Features",
    navHowItWorks: "How It Works",
    navSecurity: "Clinical Safety",
    navPortals: "Access Portals",
    setLocation: "Set location",
    signIn: "Sign in ↗",
    signOut: "Sign out",
    eyebrow: "A CALMER WAY TO MANAGE HEALTHCARE",
    hero1: "Your health story,",
    hero2: "in one place.",
    heroText: "MediLocker brings patient records, prescriptions, reports and medication routines into one beautifully organized digital experience.",
    enter: "Enter MediLocker ↗",
    seeHow: "See how it works ↓",
    sosHero: "Emergency SOS 102",
    designed: "Designed around the patient",
    records: "Records stay organized from first visit to follow-up.",
    overview: "HEALTH OVERVIEW",
    secured: "secured",
    goodMorning: "Good morning",
    profile: "PROFILE COMPLETENESS",
    keepUpdated: "Keep your medical story up to date.",
    medicalRecords: "Medical records",
    activeMeds: "Active medicines",
    nextMedication: "NEXT MEDICATION",
    afterLunch: "After lunch · 1:30 PM",
    workspaceTitle: "Unified Sovereign Health Workspace",
    step1Title: "Unique Unit ID & Identity Isolation",
    step1Text: "Sign up to generate an ABHA-aligned ML-XXX-XXX identifier. One unique user per email address with zero cross-leakage.",
    step2Title: "Multimodal Clinical AI Pipelines",
    step2Text: "Upload prescriptions, speech intake, or lab tests. Mistral AI extracts diagnoses, predicted conditions, and clinical test schedules.",
    step3Title: "Time-Bound 6-Digit Doctor Access",
    step3Text: "Doctor searches by Unit ID (revealing only Name & DOB). Patient generates a 15-min passcode to unlock records for 30m–7d.",
    badgeAbha: "ABHA Aligned",
    badgeRealtime: "Real-Time Sync",
    badgeOtp: "Time-Bound OTP",
    badgeMistral: "Mistral Guardrails",
    trust1Title: "100% Patient Control",
    trust1Desc: "Instant 1-click access revocation",
    trust2Title: "ACID Database Engine",
    trust2Desc: "Enterprise PostgreSQL storage",
    trust3Title: "15-Min Dynamic OTP",
    trust3Desc: "6-digit code for clinical access",
    trust4Title: "Zero PHI Search Leak",
    trust4Desc: "Only Name & DOB on provider search",
    featuresEyebrow: "SOVEREIGN HEALTH ARCHITECTURE",
    featuresTitle: "Engineered for Complete Clinical Continuity.",
    featuresSubtitle: "A coordinated digital ecosystem bridging patients, attending physicians, and emergency hospital networks in real time.",
    featVaultTitle: "Sovereign Health Vault & Ongoing Care",
    featVaultLive: "Live & Encrypted",
    featVaultS1Title: "Consultation Date & Course Tracking",
    featVaultS1Text: "Upload prescriptions and lab records with the verified clinical consultation date. Ongoing medications stay active while completed courses archive cleanly.",
    featVaultS2Title: "Prescriptions & Diagnostics Inline Viewer",
    featVaultS2Text: "Securely review uploaded medical records via authenticated inline viewer with instant MIME-typed streaming and zero data leakage.",
    featVaultS3Title: "Smart 12 AM Reset & 2-Day Refill Prediction",
    featVaultS3Text: "Checklist renewal across Morning, Afternoon, and Night slots, paired with automated predictive warnings 2 days before medication stock runs out.",
    featDoctorTitle: "Doctor Clinical Suite & Rapid Triage",
    featDoctorLive: "Verified Practitioners",
    featDoctorS1Title: "Zero PHI Unit ID Search & OTP Unlock",
    featDoctorS1Text: "Search patient profiles strictly by Unit ID revealing only Name and DOB until the patient grants a 15-minute 6-digit OTP passcode.",
    featDoctorS2Title: "Vaidya 30s Rapid OPD Synthesis",
    featDoctorS2Text: "Instant 30-second patient chart briefing with dual NAMASTE + WHO ICD-11 Chapter 26 terminology and HL7 FHIR export.",
    featDoctorS3Title: "Directory & Geographic Practice Matching",
    featDoctorS3Text: "Explore verified practitioners filtered by 'Previously Consulted' and 'In Your Area' local geographic matching.",
    featHospTitle: "Hospital Emergency & Touch Kiosks",
    featHospLive: "Emergency Ready",
    featHospS1Title: "Emergency 1-Second QR Profile Scanner",
    featHospS1Text: "Instant scanning of patient sovereign QR code gives emergency staff critical allergies, blood group, and emergency contact in under 1 second.",
    featHospS2Title: "OPD Walk-In Touch Kiosk with Regional Voice",
    featHospS2Text: "Interactive anatomical body map with vernacular audio prompts generating instant queue tickets and sovereign vault files.",
    featHospS3Title: "Ambulance SOS 102 & Immutable Audit Trail",
    featHospS3Text: "1-tap emergency dispatch paired with tamper-proof cryptographic audit logs tracking all access events.",
    access: "ACCESS PORTALS",
    choosePortal: "Choose your care portal.",
    portalText: "Every role gets a focused experience, while the patient's medical story remains at the center.",
    patient: "Patient",
    doctor: "Doctor",
    hospital: "Hospital",
    patientPortal: "Patient Portal",
    patientPortalDesc: "Manage records, daily to-dos, cabinet inventory, and OTP delegations.",
    doctorPortal: "Doctor Portal",
    doctorPortalDesc: "Search patients by Unit ID, review verified history, and conduct Vaidya OPD triage.",
    hospitalPortal: "Hospital Portal",
    hospitalPortalDesc: "Institutional patient records coordination, staff allocations, and audit oversight.",
    footer: "A sovereign digital sanctuary for organized healthcare.",
    footerSub: "Aligned with Ayushman Bharat Digital Mission (ABDM) architectural standards. Powered by live PostgreSQL.",
    patientVaultHeader: "Patient Health Vault",
    doctorSuiteHeader: "Doctor Clinical Suite",
    hospitalHeader: "Hospital & Emergency",
    patientSpaceTitle: "Patient Sovereign Space",
    doctorSuiteTitle: "Doctor / Clinical Suite",
    hospitalPortalTitle: "Hospital & Emergency Portal",
    dashboard: "Dashboard",
    profilePage: "My Profile & QR",
    recordsPage: "Medical Records",
    uploadPage: "Upload Documents",
    todoPage: "Medication To-Do",
    timelinePage: "Health Timeline",
    inventoryPage: "Medicine Cabinet",
    aiCompanionPage: "Medi-AI Companion",
    vaidyaPage: "Vaidya 30s Chart",
    delegationPage: "Consent & Access",
    kioskPage: "OPD Touch Kiosk",
    scannerPage: "Emergency QR Scanner",
    hospitalDoctorsPage: "Hospital Doctors & Staff",
    addDoctorBtn: "Add Doctor to Organization",
  }
};

const base = T.en;

T.hi = {
  ...base,
  unitId: "यूनिक Unit ID",
  newHere: "MediLocker पर नए हैं?",
  signUp: "खाता बनाएं →",
  signupLabel: "पंजीकरण",
  signupTitle: "अपना MediLocker बनाएं।",
  navFeatures: "विशेषताएं",
  navHowItWorks: "कार्यप्रणाली",
  navSecurity: "चिकित्सीय सुरक्षा",
  navPortals: "पोर्टल",
  setLocation: "स्थान सेट करें",
  signIn: "साइन इन ↗",
  signOut: "साइन आउट",
  eyebrow: "स्वास्थ्य प्रबंधन का सरल व सुरक्षित तरीका",
  hero1: "आपकी स्वास्थ्य कहानी,",
  hero2: "एक ही सुरक्षित स्थान पर।",
  heroText: "MediLocker मरीज के मेडिकल रिकॉर्ड, प्रिस्क्रिप्शन, रिपोर्ट और दैनिक दवाओं की दिनचर्या को एक सुंदर व सुव्यवस्थित डिजिटल अनुभव में लाता है।",
  enter: "MediLocker में प्रवेश करें ↗",
  seeHow: "देखें कैसे काम करता है ↓",
  sosHero: "आपातकालीन SOS 102",
  designed: "मरीज को केंद्र में रखकर निर्मित",
  records: "पहली मुलाकात से फॉलो-अप तक रिकॉर्ड सुरक्षित और व्यवस्थित रहते हैं।",
  overview: "स्वास्थ्य अवलोकन",
  secured: "सुरक्षित",
  goodMorning: "सुप्रभात",
  profile: "प्रोफाइल पूर्णता",
  keepUpdated: "अपनी चिकित्सा जानकारी हमेशा अपडेट रखें।",
  medicalRecords: "मेडिकल रिकॉर्ड",
  activeMeds: "सक्रिय दवाइयाँ",
  nextMedication: "अगली दवा",
  afterLunch: "दोपहर के भोजन के बाद · 1:30",
  workspaceTitle: "एकीकृत संप्रभु स्वास्थ्य वर्कस्पेस",
  step1Title: "यूनिक यूनिट आईडी व पहचान अलगाव",
  step1Text: "ABHA-अनुरूप ML-XXX-XXX पहचानकर्ता बनाएं। प्रति ईमेल एक ही सुरक्षित खाता जिससे डेटा लीक का कोई खतरा नहीं।",
  step2Title: "मल्टीमॉडल क्लिनिकल एआई पाइपलाइन",
  step2Text: "प्रिस्क्रिप्शन, वॉइस इंटेक या लैब टेस्ट अपलोड करें। एआई तुरंत निदान व जांच की सूची निकालता है।",
  step3Title: "समय-सीमाबद्ध 6-अंकीय डॉक्टर एक्सेस",
  step3Text: "डॉक्टर यूनिट आईडी से सर्च करते हैं (केवल नाम व जन्मतिथि दिखती है)। मरीज 15-मिनट का ओटीपी देकर रिकॉर्ड्स अनलॉक करते हैं।",
  badgeAbha: "ABHA अनुरूप",
  badgeRealtime: "रियल-टाइम सिंक",
  badgeOtp: "समय-बद्ध OTP",
  badgeMistral: "एआई सुरक्षा गार्डरेल्स",
  trust1Title: "100% मरीज का पूर्ण नियंत्रण",
  trust1Desc: "1-क्लिक में तुरंत एक्सेस रद्द करें",
  trust2Title: "ACID डेटाबेस इंजन",
  trust2Desc: "एंटरप्राइज PostgreSQL स्टोरेज",
  trust3Title: "15-मिनट डायनामिक OTP",
  trust3Desc: "चिकित्सीय एक्सेस हेतु 6-अंकीय कोड",
  trust4Title: "शून्य डेटा लीक सर्च",
  trust4Desc: "सर्च पर केवल नाम व जन्मतिथि दृश्यमान",
  featuresEyebrow: "संप्रभु स्वास्थ्य वास्तुकला",
  featuresTitle: "संपूर्ण क्लिनिकल निरंतरता हेतु निर्मित।",
  featuresSubtitle: "मरीजों, डॉक्टरों और आपातकालीन अस्पताल नेटवर्क को रियल-टाइम में जोड़ने वाला डिजिटल प्लेटफॉर्म।",
  featVaultTitle: "संप्रभु स्वास्थ्य वॉल्ट व निरंतर देखभाल",
  featVaultLive: "लाइव व एन्क्रिप्टेड",
  featVaultS1Title: "परामर्श तिथि व सक्रिय दवा ट्रैकिंग",
  featVaultS1Text: "सत्यापित परामर्श तिथि के साथ प्रिस्क्रिप्शन जोड़ें। चल रही दवाएं एक्टिव रहती हैं तथा पूर्ण दवाएं सुरक्षित संग्रहीत होती हैं।",
  featVaultS2Title: "प्रिस्क्रिप्शन व जांच रिपोर्ट इनलाइन व्यूअर",
  featVaultS2Text: "बिना किसी लोकल स्टोरेज लीक के सुरक्षित इनलाइन व्यूअर द्वारा मेडिकल रिकॉर्ड्स देखें।",
  featVaultS3Title: "मध्यरात्रि 12:00 बजे रीसेट व 2-दिन पूर्व रिफिल अलर्ट",
  featVaultS3Text: "सुबह, दोपहर और रात के स्लॉट का स्वचालित नवीनीकरण और दवा समाप्त होने से 2 दिन पहले अलर्ट।",
  featDoctorTitle: "डॉक्टर क्लिनिकल सूट व त्वरित ट्रायज",
  featDoctorLive: "सत्यापित चिकित्सक",
  featDoctorS1Title: "जीरो डेटा लीक सर्च व OTP अनलॉक",
  featDoctorS1Text: "यूनिट आईडी से मरीज खोजें जहां केवल नाम व जन्मतिथि दिखती है जब तक मरीज 6-अंकीय ओटीपी न दे।",
  featDoctorS2Title: "वैद्य 30s त्वरित ओपीडी संश्लेषण",
  featDoctorS2Text: "NAMASTE और WHO ICD-11 कोडिंग व HL7 FHIR एक्सपोर्ट के साथ 30 सेकंड में मरीज का संपूर्ण चार्ट सारांश।",
  featDoctorS3Title: "चिकित्सक निर्देशिका व स्थानीय मैचिंग",
  featDoctorS3Text: "पहले परामर्श लिए गए तथा अपने क्षेत्र के निकटतम डॉक्टरों को तुरंत खोजें।",
  featHospTitle: "अस्पताल आपातकालीन व टच कियोस्क",
  featHospLive: "आपातकाल हेतु तैयार",
  featHospS1Title: "आपातकालीन 1-सेकंड QR प्रोफाइल स्कैनर",
  featHospS1Text: "मरीज के संप्रभु क्यूआर को स्कैन कर 1 सेकंड में एलर्जी, ब्लड ग्रुप व इमरजेंसी कांटेक्ट प्राप्त करें।",
  featHospS2Title: "क्षेत्रीय वॉइस युक्त ओपीडी वॉक-इन कियोस्क",
  featHospS2Text: "शारीरिक अंग मैप व मातृभाषा वॉइस गाइडेंस के साथ तुरंत ओपीडी पर्ची प्राप्त करें।",
  featHospS3Title: "एंबुलेंस SOS 102 व सुरक्षित ऑडिट लॉग",
  featHospS3Text: "1-टैप आपातकालीन सहायता व प्रत्येक एक्सेस का सुरक्षित डिजिटल ऑडिट लॉग।",
  access: "एक्सेस पोर्टल",
  choosePortal: "अपना केयर पोर्टल चुनें।",
  portalText: "हर भूमिका के लिए विशिष्ट अनुभव, जबकि मरीज की मेडिकल कहानी सदैव केंद्र में रहती है।",
  patient: "मरीज",
  doctor: "डॉक्टर",
  hospital: "अस्पताल",
  patientPortal: "मरीज पोर्टल",
  patientPortalDesc: "रिकॉर्ड, दैनिक कार्य, दवा कैबिनेट और ओटीपी सहमति प्रबंधित करें।",
  doctorPortal: "डॉक्टर पोर्टल",
  doctorPortalDesc: "यूनिट आईडी से मरीज खोजें, रिकॉर्ड देखें और वैद्य ओपीडी सेवा दें।",
  hospitalPortal: "अस्पताल पोर्टल",
  hospitalPortalDesc: "संस्थागत रिकॉर्ड समन्वय, कर्मचारी आवंटन और ऑडिट निगरानी।",
  footer: "सुव्यवस्थित स्वास्थ्य सेवा के लिए एक सुरक्षित डिजिटल घर।",
  footerSub: "आयुष्मान भारत डिजिटल मिशन (ABDM) मानकों के अनुरूप। लाइव PostgreSQL द्वारा संचालित।",
  patientVaultHeader: "मरीज स्वास्थ्य वॉल्ट",
  doctorSuiteHeader: "डॉक्टर क्लिनिकल सूट",
  hospitalHeader: "अस्पताल व आपातकाल",
  patientSpaceTitle: "मरीज संप्रभु स्पेस",
  doctorSuiteTitle: "डॉक्टर क्लिनिकल सूट",
  hospitalPortalTitle: "अस्पताल व आपातकालीन पोर्टल",
  dashboard: "डैशबोर्ड",
  profilePage: "मेरी प्रोफाइल व QR",
  recordsPage: "मेडिकल रिकॉर्ड",
  uploadPage: "दस्तावेज अपलोड",
  todoPage: "दवा दिनचर्या",
  timelinePage: "स्वास्थ्य टाइमलाइन",
  inventoryPage: "दवा कैबिनेट",
  aiCompanionPage: "मेडी-एआई साथी",
  vaidyaPage: "वैद्य 30s चार्ट",
  delegationPage: "सहमति व एक्सेस",
  kioskPage: "ओपीडी टच कियोस्क",
  scannerPage: "इमरजेंसी QR स्कैनर",
};

T.bn = {
  ...base,
  unitId: "ইউনিক Unit ID",
  newHere: "MediLocker-এ নতুন?",
  signUp: "অ্যাকাউন্ট তৈরি করুন →",
  signupLabel: "রেজিস্ট্রেশন",
  signupTitle: "আপনার MediLocker তৈরি করুন।",
  navFeatures: "ফিচারসমূহ",
  navHowItWorks: "কাজের ধারা",
  navSecurity: "ক্লিনিকাল নিরাপত্তা",
  navPortals: "পোর্টাল",
  setLocation: "অবস্থান সেট করুন",
  signIn: "সাইন ইন ↗",
  signOut: "সাইন আউট",
  eyebrow: "স্বাস্থ্য ব্যবস্থাপনার সহজ ও সুশৃঙ্খল উপায়",
  hero1: "আপনার স্বাস্থ্যকথা,",
  hero2: "একই নিরাপদ ঠিকানায়।",
  heroText: "MediLocker রোগীর সব প্রেসক্রিপশন, রিপোর্ট এবং ওষুধের রুটিনকে একটি সুন্দর ও গোছানো ডিজিটাল অভিজ্ঞতায় নিয়ে আসে।",
  enter: "MediLocker-এ প্রবেশ করুন ↗",
  seeHow: "কীভাবে কাজ করে দেখুন ↓",
  sosHero: "জরুরি SOS ১০২",
  designed: "রোগীকে কেন্দ্র করে নির্মিত",
  records: "প্রথম সাক্ষাৎ থেকে পরবর্তী ফলো-আপ পর্যন্ত সমস্ত রেকর্ড সুরক্ষিত থাকে।",
  overview: "স্বাস্থ্য পর্যালোচনা",
  secured: "সুরক্ষিত",
  goodMorning: "সুপ্রভাত",
  profile: "প্রোফাইল সম্পূর্ণতা",
  keepUpdated: "চিকিৎসার তথ্য সর্বদা আপডেট রাখুন।",
  medicalRecords: "চিকিৎসা রেকর্ড",
  activeMeds: "চলমান ওষুধ",
  nextMedication: "পরবর্তী ওষুধ",
  afterLunch: "দুপুরের খাবারের পর · ১:৩০",
  workspaceTitle: "সার্বভৌম স্বাস্থ্য ওয়ার্কস্পেস",
  step1Title: "ইউনিক ইউনিট আইডি ও সম্পূর্ণ গোপনীয়তা",
  step1Text: "ABHA-অনুমোদিত ML-XXX-XXX আইডি তৈরি করুন। প্রতিটি ইমেলের জন্য একটিমাত্র অনন্য প্রোফাইল।",
  step2Title: "মাল্টিমোডাল ক্লিনিকাল এআই ইঞ্জিন",
  step2Text: "প্রেসক্রিপশন বা রিপোর্ট আপলোড করুন। এআই স্বয়ংক্রিয়ভাবে রোগ ও টেস্টের তালিকা তৈরি করে দেয়।",
  step3Title: "১৫ মিনিটের ডায়নামিক ওটিপি অ্যাক্সেস",
  step3Text: "ডাক্তার ইউনিট আইডি দিয়ে খুঁজলে শুধু নাম ও জন্মতারিখ দেখা যাবে। ওটিপি দিলে তবেই রেকর্ড আনলক হবে।",
  badgeAbha: "ABHA অনুমোদিত",
  badgeRealtime: "রিয়েল-টাইম সিঙ্ক",
  badgeOtp: "সময়-সীমিত OTP",
  badgeMistral: "এআই সুরক্ষা বলয়",
  trust1Title: "১০০% রোগীর পূর্ণ নিয়ন্ত্রণ",
  trust1Desc: "১-ক্লিকে তাৎক্ষণিক অ্যাক্সেস প্রত্যাহার",
  trust2Title: "ACID ডেটাবেস ইঞ্জিন",
  trust2Desc: "এন্টারপ্রাইজ PostgreSQL স্টোরেজ",
  trust3Title: "১৫-মিনিট ডায়নামিক OTP",
  trust3Desc: "ক্লিনিকাল অ্যাক্সেসের জন্য ৬-সংখ্যার কোড",
  trust4Title: "জিরো ডেটা লিক সার্চ",
  trust4Desc: "অনুসন্ধানে কেবল নাম ও জন্মতারিখ দৃশ্যমান",
  featuresEyebrow: "সার্বভৌম স্বাস্থ্য পরিকাঠামো",
  featuresTitle: "নিরবচ্ছিন্ন চিকিৎসার জন্য বিশেষভাবে তৈরি।",
  featuresSubtitle: "রোগী, চিকিৎসক এবং জরুরি হাসপাতাল নেটওয়ার্কের মধ্যে সরাসরি সমন্বয়কারী ডিজিটাল সেতু।",
  featVaultTitle: "সার্বভৌম স্বাস্থ্য ভল্ট ও নিয়মিত চিকিৎসা",
  featVaultLive: "লাইভ ও এনক্রিপ্টেড",
  featVaultS1Title: "পরামর্শের তারিখ ও চলমান ওষুধের ট্র্যাক",
  featVaultS1Text: "সঠিক পরামর্শের তারিখ দিয়ে প্রেসক্রিপশন সংরক্ষণ করুন। রুটিনের ওষুধ চালু থাকে ও শেষ হওয়া কোর্স আর্কাইভে জমা হয়।",
  featVaultS2Title: "প্রেসক্রিপশন ও ডায়াগনস্টিক ইনলাইন ভিউয়ার",
  featVaultS2Text: "নিরাপদ ইনলাইন ভিউয়ারের সাহায্যে কোনো ফাইল লিক ছাড়া প্রেসক্রিপশন ও রিপোর্ট সহজে দেখুন।",
  featVaultS3Title: "রাত ১২টায় স্বয়ংক্রিয় রিফ্রেশ ও ২-দিনের রিফিল অ্যালার্ট",
  featVaultS3Text: "সকাল, দুপুর ও রাতের ওষুধ চেকলিস্ট মধ্যরাতে রিফ্রেশ হয় এবং ওষুধ ফুরনোর ২ দিন আগে আগাম সতর্কতা মেলে।",
  featDoctorTitle: "ডাক্তার ক্লিনিকাল স্যুট ও দ্রুত ট্রায়াজ",
  featDoctorLive: "অনুমোদিত চিকিৎসকবৃন্দ",
  featDoctorS1Title: "জিরো ডেটা লিক সার্চ ও OTP অনুমোদন",
  featDoctorS1Text: "ইউনিট আইডি দিয়ে সার্চ করলে কেবল নাম ও জন্মতারিখ দেখা যাবে যতক্ষণ না রোগী ৬-সংখ্যার ওটিপি দেন।",
  featDoctorS2Title: "বৈদ্য ৩০ সেকেন্ড ওপিডি সারাংশ",
  featDoctorS2Text: "NAMASTE এবং WHO ICD-11 কোডিংসহ মাত্র ৩০ সেকেন্ডে রোগীর সম্পূর্ণ ক্লিনিকাল চার্ট ব্রিফিং।",
  featDoctorS3Title: "নিকটবর্তী ডাক্তার নির্দেশিকা ও বুকিং",
  featDoctorS3Text: "পূর্ববর্তী ডাক্তার ও স্থানীয় অঞ্চলের বিশিষ্ট চিকিৎসকদের সহজে খুঁজুন।",
  featHospTitle: "হাসপাতাল ইমার্জেন্সি ও টাচ কিয়স্ক",
  featHospLive: "জরুরি সেবায় সর্বদা প্রস্তুত",
  featHospS1Title: "জরুরি ১-সেকেন্ড QR প্রোফাইল স্ক্যানার",
  featHospS1Text: "জরুরি পরিস্থিতিতে রোগীর কিউআর স্ক্যান করে ১ সেকেন্ডে রক্তের গ্রুপ, অ্যালার্জি ও জরুরি যোগাযোগ পান।",
  featHospS2Title: "বাংলা ভয়েস নির্দেশিকাযুক্ত টাচ কিয়স্ক",
  featHospS2Text: "শরীরের ব্যথার অঙ্গ নির্বাচন করে বা মুখে কথা বলে মুহূর্তের মধ্যে ওপিডি টিকিট পান।",
  featHospS3Title: "অ্যাম্বুলেন্স SOS ১০২ ও অডিট লগ",
  featHospS3Text: "১-ট্যাপে এমার্জেন্সি কল ও প্রতিটি রেকর্ডে প্রবেশের অপরিবর্তনযোগ্য ডিজিটাল নিরাপত্তা লগ।",
  access: "অ্যাক্সেস পোর্টাল",
  choosePortal: "আপনার কেয়ার পোর্টাল বেছে নিন।",
  portalText: "প্রতিটি ভূমিকার জন্য আলাদা অভিজ্ঞতা, আর রোগীর চিকিৎসার গল্প থাকে কেন্দ্রে।",
  patient: "রোগী",
  doctor: "ডাক্তার",
  hospital: "হাসপাতাল",
  patientPortal: "রোগী পোর্টাল",
  patientPortalDesc: "রেকর্ড, দৈনন্দিন কাজ, ওষুধের ক্যাবিনেট এবং ওটিপি প্রতিনিধি পরিচালনা করুন।",
  doctorPortal: "ডাক্তার পোর্টাল",
  doctorPortalDesc: "ইউনিট আইডি দিয়ে রোগী খুঁজুন, রেকর্ড দেখুন এবং বৈদ্য ওপিডি ট্রায়াজ করুন।",
  hospitalPortal: "হাসপাতাল পোর্টাল",
  hospitalPortalDesc: "প্রতিষ্ঠানগত রেকর্ড সমন্বয়, স্টাফ পরিচালনা এবং অডিট নজরদারি।",
  footer: "সুশৃঙ্খল স্বাস্থ্যসেবার জন্য একটি নিরাপদ ডিজিটাল ঠিকানা।",
  footerSub: "আয়ুষ্মান ভারত ডিজিটাল মিশন (ABDM) স্থাপত্য মান অনুযায়ী নির্মিত। লাইভ PostgreSQL দ্বারা চালিত।",
  patientVaultHeader: "রোগীর স্বাস্থ্য ভল্ট",
  doctorSuiteHeader: "ডাক্তার ক্লিনিকাল স্যুট",
  hospitalHeader: "হাসপাতাল ও জরুরি বিভাগ",
  patientSpaceTitle: "রোগী সার্বভৌম স্পেস",
  doctorSuiteTitle: "ডাক্তার ক্লিনিকাল স্যুট",
  hospitalPortalTitle: "হাসপাতাল ও জরুরি পোর্টাল",
  dashboard: "ড্যাশবোর্ড",
  profilePage: "আমার প্রোফাইল ও QR",
  recordsPage: "চিকিৎসা রেকর্ড",
  uploadPage: "ডকুমেন্ট আপলোড",
  todoPage: "ওষুধের রুটিন",
  timelinePage: "স্বাস্থ্য টাইমলাইন",
  inventoryPage: "ওষুধের কেবিনেট",
  aiCompanionPage: "মেডি-এআই সঙ্গী",
  vaidyaPage: "বৈদ্য ৩০ সে. চার্ট",
  delegationPage: "সম্মতি ও অ্যাক্সেস",
  kioskPage: "ওপিডি টাচ কিয়স্ক",
  scannerPage: "ইমার্জেন্সি QR স্ক্যানার",
};

T.mr = {
  ...base,
  unitId: "युनिक Unit ID",
  newHere: "MediLocker वर नवीन आहात?",
  signUp: "खाते तयार करा →",
  navFeatures: "वैशिष्ट्ये",
  navHowItWorks: "कार्यपद्धती",
  navSecurity: "वैद्यकीय सुरक्षा",
  navPortals: "पोर्टल",
  setLocation: "स्थान सेट करा",
  signIn: "साइन इन ↗",
  signOut: "साइन आउट",
  eyebrow: "आरोग्य व्यवस्थापनाचा सुलभ व सुरक्षित मार्ग",
  hero1: "तुमची आरोग्यकथा,",
  hero2: "एकाच सुरक्षित ठिकाणी.",
  heroText: "MediLocker रुग्णांचे रेकॉर्ड, प्रिस्क्रिप्शन, रिपोर्ट आणि औषधांची दिनचर्या एका व्यवस्थित डिजिटल अनुभवात आणते.",
  enter: "MediLocker मध्ये प्रवेश करा ↗",
  seeHow: "कसे कार्य करते ते पहा ↓",
  sosHero: "आपत्कालीन SOS 102",
  designed: "रुग्णाला केंद्रस्थानी ठेवून तयार",
  records: "पहिल्या भेटीपासून फॉलो-अपपर्यंत रेकॉर्ड सुरक्षित राहतात.",
  overview: "आरोग्य आढावा",
  secured: "सुरक्षित",
  goodMorning: "सुप्रभात",
  profile: "प्रोफाइल पूर्णता",
  keepUpdated: "तुमची वैद्यकीय माहिती नेहमी अद्ययावत ठेवा.",
  medicalRecords: "वैद्यकीय रेकॉर्ड",
  activeMeds: "सक्रिय औषधे",
  nextMedication: "पुढील औषध",
  afterLunch: "दुपारच्या जेवणानंतर · 1:30",
  workspaceTitle: "एकात्मिक सार्वभौम आरोग्य वर्कस्पेस",
  trust1Title: "१००% रुग्णांचे नियंत्रण",
  trust1Desc: "१-क्लिकमध्ये तत्काळ प्रवेश रद्द",
  trust2Title: "ACID डेटाबेस इंजिन",
  trust2Desc: "एंटरप्राइज PostgreSQL स्टोरेज",
  trust3Title: "१५-मिनिट डायनॅमिक OTP",
  trust3Desc: "क्लिनिकल प्रवेशासाठी ६-अंकी कोड",
  trust4Title: "झिरो डेटा लीक सर्च",
  trust4Desc: "शोधताना केवळ नाव व जन्मतारीख दृश्यमान",
  featuresEyebrow: "सार्वभौम आरोग्य रचना",
  featuresTitle: "संपूर्ण क्लिनिकल सातत्यासाठी सज्ज.",
  featuresSubtitle: "रुग्ण, वैद्यकीय तज्ज्ञ आणि आपत्कालीन रुग्णालयांना जोडणारी प्रणाली.",
  featVaultTitle: "आरोग्य वॉल्ट आणि चालू उपचार",
  featVaultLive: "थेट व एन्क्रिप्टेड",
  featVaultS1Title: "सल्लामसलत तारीख आणि औषध ट्रॅकिंग",
  featVaultS1Text: "तपासणीच्या तारखेनुसार प्रिस्क्रिप्शन जतन करा. चालू औषधे सक्रिय राहतात व पूर्ण झालेले कोर्सेस सुरक्षित संग्रहित होतात.",
  featVaultS2Title: "प्रिस्क्रिप्शन व लॅब रिपोर्ट इनलाइन व्ह्यूअर",
  featVaultS2Text: "कोणत्याही डेटा गळतीशिवाय सुरक्षित इनलाइन व्ह्यूअरने रेकॉर्ड्स तपासा.",
  featVaultS3Title: "मध्यरात्री १२ वाजता रीसेट व २ दिवस आधी रिफिल अलर्ट",
  featVaultS3Text: "सकाळ, दुपार आणि रात्रीच्या गोळ्यांची यादी दररोज मध्यरात्री रीसेट होते व औषध संपण्यापूर्वी २ दिवस आधी सूचना मिळते.",
  featDoctorTitle: "डॉक्टर क्लिनिकल सूट व ओपीडी ट्रायज",
  featDoctorLive: "प्रमाणित डॉक्टर",
  featDoctorS1Title: "शून्य डेटा लीक सर्च व OTP अनलॉक",
  featDoctorS1Text: "युनिट आयडीने रुग्ण शोधल्यावर फक्त नाव व जन्मतारीख दिसते, संपूर्ण रेकॉर्ड्ससाठी ६-अंकी ओटीपी आवश्यक असतो.",
  featDoctorS2Title: "वैद्य ३० सेकंद ओपीडी संश्लेषण",
  featDoctorS2Text: "NAMASTE आणि WHO ICD-11 मानकांसह अवघ्या ३० सेकंदात रुग्णाचा संक्षिप्त वैद्यकीय सारांश.",
  featDoctorS3Title: "स्थानिक डॉक्टर डिरेक्टरी",
  featDoctorS3Text: "पूर्वी सल्ला घेतलेले व परिसरातील तज्ज्ञ डॉक्टर्स त्वरित शोधा.",
  featHospTitle: "रुग्णालय आपत्कालीन व टच किऑस्क",
  featHospLive: "तातडीच्या सेवेसाठी सज्ज",
  featHospS1Title: "आपत्कालीन १-सेकंद QR प्रोफाइल स्कॅनर",
  featHospS1Text: "रुग्णाचा क्यूआर स्कॅन करून १ सेकंदात रक्तगट, ॲलर्जी व इमर्जन्सी संपर्क मिळवा.",
  featHospS2Title: "मराठी व्हॉइस गाईड असलेले टच किऑस्क",
  featHospS2Text: "शरीरावरील वेदनेचा भाग निवडून किंवा आवाजाद्वारे त्वरित ओपीडी पावती मिळवा.",
  featHospS3Title: "ॲम्ब्युलन्स SOS १०२ व ऑडिट ट्रेल",
  featHospS3Text: "१-टॅप आपत्कालीन कॉल आणि प्रत्येक तपासणीचा सुरक्षित डिजिटल लॉग.",
  access: "प्रवेश पोर्टल",
  choosePortal: "तुमचा केअर पोर्टल निवडा.",
  portalText: "प्रत्येक भूमिकेसाठी वेगळा अनुभव, आणि रुग्णाची वैद्यकीय कथा केंद्रस्थानी.",
  patient: "रुग्ण",
  doctor: "डॉक्टर",
  hospital: "रुग्णालय",
  patientPortal: "रुग्ण पोर्टल",
  patientPortalDesc: "रेकॉर्ड, दैनंदिन कामे, औषध कॅबिनेट आणि ओटीपी संमती व्यवस्थापित करा.",
  doctorPortal: "डॉक्टर पोर्टल",
  doctorPortalDesc: "युनिट आयडीने रुग्ण शोधा, इतिहास तपासा आणि वैद्य ओपीडी ट्रायज करा.",
  hospitalPortal: "रुग्णालय पोर्टल",
  hospitalPortalDesc: "संस्थात्मक रेकॉर्ड समन्वय, कर्मचारी वाटप आणि ऑडिट निरीक्षण.",
  footer: "सुव्यवस्थित आरोग्यसेवेसाठी एक सुरक्षित डिजिटल ठिकाण.",
  footerSub: "आयुष्मान भारत डिजिटल मिशन (ABDM) मानकांनुसार तयार. थेट PostgreSQL द्वारे समर्थित.",
  patientVaultHeader: "रुग्ण आरोग्य वॉल्ट",
  doctorSuiteHeader: "डॉक्टर क्लिनिकल सूट",
  hospitalHeader: "रुग्णालय व आपत्कालीन",
  patientSpaceTitle: "रुग्ण सार्वभौम स्पेस",
  doctorSuiteTitle: "डॉक्टर क्लिनिकल सूट",
  hospitalPortalTitle: "रुग्णालय व आपत्कालीन पोर्टल",
  dashboard: "डॅशबोर्ड",
  profilePage: "माझे प्रोफाइल व QR",
  recordsPage: "वैद्यकीय रेकॉर्ड",
  uploadPage: "डॉक्युमेंट अपलोड",
  todoPage: "औषध दिनचर्या",
  timelinePage: "आरोग्य टाइमलाइन",
  inventoryPage: "औषध कॅबिनेट",
  aiCompanionPage: "मेडी-एआय साथी",
  vaidyaPage: "वैद्य ३० से. चार्ट",
  delegationPage: "संमती व ॲक्सेस",
  kioskPage: "ओपीडी टच किऑस्क",
  scannerPage: "इमर्जन्सी QR स्कॅनर",
};

T.ur = {
  ...base,
  unitId: "یونٹ آئی ڈی",
  newHere: "MediLocker پر نئے ہیں؟",
  signUp: "اکاؤنٹ بنائیں →",
  navFeatures: "خصوصیات",
  navHowItWorks: "طریقہ کار",
  navSecurity: "طبی حفاظت",
  navPortals: "پورٹلز",
  setLocation: "مقام سیٹ کریں",
  signIn: "سائن اِن ↗",
  signOut: "سائن آؤٹ",
  eyebrow: "صحت کے انتظام کا آسان اور محفوظ طریقہ",
  hero1: "آپ کی صحت کی کہانی،",
  hero2: "ایک ہی محفوظ جگہ پر۔",
  heroText: "MediLocker مریض کے ریکارڈ، نسخے، رپورٹس اور ادویات کی روٹین کو ایک منظم ڈیجیٹل تجربے میں لاتا ہے۔",
  enter: "MediLocker میں داخل ہوں ↗",
  seeHow: "دیکھیں کیسے کام کرتا ہے ↓",
  sosHero: "ہنگامی SOS 102",
  designed: "مریض کو مرکز میں رکھ کر بنایا گیا",
  records: "پہلی ملاقات سے لے کر فالو اپ تک تمام ریکارڈز محفوظ رہتے ہیں۔",
  overview: "صحت کا جائزہ",
  secured: "محفوظ",
  goodMorning: "صبح بخیر",
  profile: "پروفائل کی تکمیل",
  keepUpdated: "اپنی طبی معلومات ہمیشہ اپ ڈیٹ رکھیں۔",
  medicalRecords: "طبی ریکارڈ",
  activeMeds: "فعال ادویات",
  nextMedication: "اگلی دوا",
  afterLunch: "دوپہر کے کھانے کے بعد · 1:30",
  workspaceTitle: "خود مختار ہیلتھ ورک اسپیس",
  trust1Title: "۱۰۰٪ مریض کا مکمل کنٹرول",
  trust1Desc: "فوری ایک کلک رسائی منسوخی",
  trust2Title: "ACID ڈیٹا بیس انجن",
  trust2Desc: "انٹرپرائز PostgreSQL اسٹوریج",
  trust3Title: "۱۵ منٹ متحرک OTP",
  trust3Desc: "طبی رسائی کے لیے ۶ ہندسوں کا کوڈ",
  trust4Title: "صفر ذاتی ڈیٹا لیک",
  trust4Desc: "تلاش پر صرف نام اور تاریخ پیدائش ظاہر",
  featuresEyebrow: "خود مختار ہیلتھ آرکیٹیکچر",
  featuresTitle: "مکمل طبی تسلسل کے لیے ڈیزائن کیا گیا۔",
  featuresSubtitle: "مریضوں، معالجین اور ہنگامی ہسپتال نیٹ ورک کو جوڑنے والا ڈیجیٹل پلیٹ فارم۔",
  featVaultTitle: "صحت کا والٹ اور جاری دیکھ بھال",
  featVaultLive: "محفوظ اور انکرپٹڈ",
  featVaultS1Title: "مشاورت کی تاریخ اور ادویات کی ٹریکنگ",
  featVaultS1Text: "مصدقہ تاریخ کے ساتھ نسخے محفوظ کریں۔ جاری ادویات فعال رہتی ہیں اور مکمل شدہ محفوظ ہو جاتی ہیں۔",
  featVaultS2Title: "نسخہ اور لیب رپورٹ ان لائن ویور",
  featVaultS2Text: "بغیر کسی ڈیٹا لیک کے محفوظ ان لائن ویور سے میڈیکل ریکارڈز دیکھیں۔",
  featVaultS3Title: "رات ۱۲ بجے خودکار ری سیٹ اور ریفل الرٹ",
  featVaultS3Text: "صبح، دوپہر اور رات کی ادویات روزانہ ری سیٹ ہوتی ہیں اور ختم ہونے سے ۲ دن پہلے الرٹ ملتا ہے۔",
  featDoctorTitle: "ڈاکٹر کلینکل سوٹ اور فوری تشخیص",
  featDoctorLive: "مصدقہ معالجین",
  featDoctorS1Title: "زیرو ڈیٹا لیک تلاش اور OTP اجازت",
  featDoctorS1Text: "یونٹ آئی ڈی سے مریض تلاش کریں جہاں صرف نام اور تاریخ پیدائش نظر آتی ہے جب تک مریض او ٹی پی نہ دے۔",
  featDoctorS2Title: "ویدیہ ۳۰ سیکنڈ او پی ڈی خلاصہ",
  featDoctorS2Text: "NAMASTE اور WHO ICD-11 کوڈنگ کے ساتھ صرف ۳۰ سیکنڈ میں مریض کا تفصیلی جائزہ۔",
  featDoctorS3Title: "ڈاکٹر ڈائرکٹری اور علاقائی تلاش",
  featDoctorS3Text: "پہلے سے معائنہ کرنے والے اور قریبی ڈاکٹروں کو فوری تلاش کریں۔",
  featHospTitle: "ہسپتال ایمرجنسی اور ٹچ کیوسک",
  featHospLive: "ہنگامی حالات کے لیے تیار",
  featHospS1Title: "ہنگامی ۱ سیکنڈ QR پروفائل اسکینر",
  featHospS1Text: "مریض کا کیو آر اسکین کر کے ۱ سیکنڈ میں بلڈ گروپ، الرجی اور ایمرجنسی رابطہ حاصل کریں۔",
  featHospS2Title: "اردو آواز کی رہنمائی والا ٹچ کیوسک",
  featHospS2Text: "جسم پر تکلیف کی جگہ چھو کر یا بول کر فوری او پی ڈی پرچی حاصل کریں۔",
  featHospS3Title: "ایمبولینس SOS 102 اور آڈٹ لاگ",
  featHospS3Text: "ایک کلک پر ایمرجنسی کال اور ریکارڈز تک ہر رسائی کا محفوظ لاگ۔",
  access: "رسائی پورٹلز",
  choosePortal: "اپنا کیئر پورٹل منتخب کریں۔",
  portalText: "ہر کردار کے لیے الگ تجربہ، جبکہ مریض کی طبی کہانی مرکز میں رہتی ہے۔",
  patient: "مریض",
  doctor: "ڈاکٹر",
  hospital: "ہسپتال",
  patientPortal: "مریض پورٹل",
  patientPortalDesc: "ریکارڈز، روزمرہ کام، ادویات کیبنٹ اور او ٹی پی وفود کا انتظام کریں۔",
  doctorPortal: "ڈاکٹر پورٹل",
  doctorPortalDesc: "یونٹ آئی ڈی سے مریض تلاش کریں اور ویدیہ او پی ڈی ٹریاج انجام دیں۔",
  hospitalPortal: "ہسپتال پورٹل",
  hospitalPortalDesc: "ادارہ جاتی ریکارڈز کوآرڈینیشن، عملہ کا انتظام اور آڈٹ نگرانی۔",
  footer: "منظم صحت کی دیکھ بھال کے لیے ایک محفوظ ڈیجیٹل مرکز۔",
  footerSub: "آیوشمان بھارت ڈیجیٹل مشن (ABDM) کے معیارات کے مطابق۔ PostgreSQL سے تقویت یافتہ۔",
  patientVaultHeader: "مریض ہیلتھ والٹ",
  doctorSuiteHeader: "ڈاکٹر کلینکل سوٹ",
  hospitalHeader: "ہسپتال اور ایمرجنسی",
  patientSpaceTitle: "مریض خودمختار اسپیس",
  doctorSuiteTitle: "ڈاکٹر کلینکل سوٹ",
  hospitalPortalTitle: "ہسپتال و ایمرجنسی پورٹل",
  dashboard: "ڈیش بورڈ",
  profilePage: "میرا پروفائل اور QR",
  recordsPage: "طبی ریکارڈ",
  uploadPage: "دستاویز اپ لوڈ",
  todoPage: "ادویات کی روٹین",
  timelinePage: "صحت ٹائم لائن",
  inventoryPage: "ادویات کیبنٹ",
  aiCompanionPage: "میڈی-اے آئی ساتھی",
  vaidyaPage: "ویدیہ ۳۰ سیکنڈ چارٹ",
  delegationPage: "رضامندی اور رسائی",
  kioskPage: "او پی ڈی ٹچ کیوسک",
  scannerPage: "ایمرجنسی QR اسکینر",
};

T.pa = {
  ...base,
  unitId: "ਯੂਨਿਟ ID",
  newHere: "MediLocker 'ਤੇ ਨਵੇਂ ਹੋ?",
  signUp: "ਖਾਤਾ ਬਣਾਓ →",
  navFeatures: "ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
  navHowItWorks: "ਕੰਮ ਕਰਨ ਦਾ ਤਰੀਕਾ",
  navSecurity: "ਕਲੀਨਿਕਲ ਸੁਰੱਖਿਆ",
  navPortals: "ਪੋਰਟਲ",
  setLocation: "ਟਿਕਾਣਾ ਸੈੱਟ ਕਰੋ",
  signIn: "ਸਾਈਨ ਇਨ ↗",
  signOut: "ਸਾਈਨ ਆਊਟ",
  eyebrow: "ਸਿਹਤ ਪ੍ਰਬੰਧਨ ਦਾ ਆਸਾਨ ਅਤੇ ਸੁਰੱਖਿਅਤ ਤਰੀਕਾ",
  hero1: "ਤੁਹਾਡੀ ਸਿਹਤ ਦੀ ਕਹਾਣੀ,",
  hero2: "ਇੱਕ ਹੀ ਸੁਰੱਖਿਅਤ ਥਾਂ 'ਤੇ।",
  heroText: "MediLocker ਮਰੀਜ਼ ਦੇ ਰਿਕਾਰਡ, ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ, ਰਿਪੋਰਟਾਂ ਅਤੇ ਦਵਾਈਆਂ ਦੀ ਰੁਟੀਨ ਨੂੰ ਇੱਕ ਆਸਾਨ ਡਿਜ਼ੀਟਲ ਅਨੁਭਵ ਵਿੱਚ ਲਿਆਉਂਦਾ ਹੈ।",
  enter: "MediLocker ਵਿੱਚ ਜਾਓ ↗",
  seeHow: "ਵੇਖੋ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ ↓",
  sosHero: "ਐਮਰਜੈਂਸੀ SOS 102",
  designed: "ਮਰੀਜ਼ ਨੂੰ ਕੇਂਦਰ ਵਿੱਚ ਰੱਖ ਕੇ ਬਣਾਇਆ ਗਿਆ",
  records: "ਪਹਿਲੀ ਮੁਲਾਕਾਤ ਤੋਂ ਲੈ ਕੇ ਫਾਲੋ-ਅੱਪ ਤੱਕ ਸਾਰੇ ਰਿਕਾਰਡ ਸੁਰੱਖਿਅਤ ਰਹਿੰਦੇ ਹਨ।",
  overview: "ਸਿਹਤ ਝਲਕ",
  secured: "ਸੁਰੱਖਿਅਤ",
  goodMorning: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ",
  profile: "ਪ੍ਰੋਫਾਈਲ ਪੂਰਨਤਾ",
  keepUpdated: "ਆਪਣੀ ਡਾਕਟਰੀ ਜਾਣਕਾਰੀ ਅੱਪਡੇਟ ਰੱਖੋ।",
  medicalRecords: "ਮੈਡੀਕਲ ਰਿਕਾਰਡ",
  activeMeds: "ਚੱਲ ਰਹੀਆਂ ਦਵਾਈਆਂ",
  nextMedication: "ਅਗਲੀ ਦਵਾਈ",
  afterLunch: "ਦੁਪਹਿਰ ਦੇ ਖਾਣੇ ਤੋਂ ਬਾਅਦ · 1:30",
  workspaceTitle: "ਏਕੀਕ੍ਰਿਤ ਸਿਹਤ ਵਰਕਸਪੇਸ",
  trust1Title: "੧੦੦% ਮਰੀਜ਼ ਦਾ ਪੂਰਾ ਕੰਟਰੋਲ",
  trust1Desc: "੧-ਕਲਿੱਕ ਨਾਲ ਤੁਰੰਤ ਐਕਸੈੱਸ ਰੱਦ ਕਰੋ",
  trust2Title: "ACID ਡਾਟਾਬੇਸ ਇੰਜਨ",
  trust2Desc: "ਐਂਟਰਪ੍ਰਾਈਜ਼ PostgreSQL ਸਟੋਰੇਜ",
  trust3Title: "੧੫-ਮਿੰਟ ਡਾਇਨਾਮਿਕ OTP",
  trust3Desc: "ਕਲੀਨਿਕਲ ਐਕਸੈੱਸ ਲਈ ੬-ਅੰਕੀ ਕੋਡ",
  trust4Title: "ਜ਼ੀਰੋ ਡਾਟਾ ਲੀਕ ਸਰਚ",
  trust4Desc: "ਖੋਜ ਵਿੱਚ ਸਿਰਫ ਨਾਮ ਅਤੇ ਜਨਮ ਮਿਤੀ ਦਿਖਾਈ ਦਿੰਦੀ ਹੈ",
  featuresEyebrow: "ਸਿਹਤ ਆਰਕੀਟੈਕਚਰ",
  featuresTitle: "ਸੰਪੂਰਨ ਕਲੀਨਿਕਲ ਨਿਰੰਤਰਤਾ ਲਈ ਤਿਆਰ।",
  featuresSubtitle: "ਮਰੀਜ਼ਾਂ, ਡਾਕਟਰਾਂ ਅਤੇ ਐਮਰਜੈਂਸੀ ਹਸਪਤਾਲ ਨੈੱਟਵਰਕ ਨੂੰ ਜੋੜਨ ਵਾਲਾ ਡਿਜੀਟਲ ਪਲੇਟਫਾਰਮ।",
  featVaultTitle: "ਸਿਹਤ ਵਾਲਟ ਅਤੇ ਨਿਯਮਤ ਦੇਖਭਾਲ",
  featVaultLive: "ਲਾਈਵ ਅਤੇ ਐਨਕ੍ਰਿਪਟਡ",
  featVaultS1Title: "ਸਲਾਹ ਮਿਤੀ ਅਤੇ ਦਵਾਈ ਟਰੈਕਿੰਗ",
  featVaultS1Text: "ਮਿਤੀ ਅਨੁਸਾਰ ਪਰਚੀਆਂ ਸੁਰੱਖਿਅਤ ਕਰੋ। ਚੱਲ ਰਹੀਆਂ ਦਵਾਈਆਂ ਸਰਗਰਮ ਰਹਿੰਦੀਆਂ ਹਨ ਅਤੇ ਪੂਰੀਆਂ ਦਵਾਈਆਂ ਆਰਕਾਈਵ ਹੋ ਜਾਂਦੀਆਂ ਹਨ।",
  featVaultS2Title: "ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ ਅਤੇ ਲੈਬ ਰਿਪੋਰਟ ਵਿਊਅਰ",
  featVaultS2Text: "ਬਿਨਾਂ ਕਿਸੇ ਡਾਟਾ ਲੀਕ ਦੇ ਸੁਰੱਖਿਅਤ ਢੰਗ ਨਾਲ ਰਿਕਾਰਡ ਦੇਖੋ।",
  featVaultS3Title: "ਰਾਤ 12 ਵਜੇ ਰੀਸੈੱਟ ਅਤੇ 2 ਦਿਨ ਪਹਿਲਾਂ ਰੀਫਿਲ ਅਲਰਟ",
  featVaultS3Text: "ਸਵੇਰ, ਦੁਪਹਿਰ ਅਤੇ ਰਾਤ ਦੀਆਂ ਦਵਾਈਆਂ ਰੋਜ਼ਾਨਾ ਰੀਸੈੱਟ ਹੁੰਦੀਆਂ ਹਨ ਅਤੇ ਮੁੱਕਣ ਤੋਂ 2 ਦਿਨ ਪਹਿਲਾਂ ਅਲਰਟ ਮਿਲਦਾ ਹੈ।",
  featDoctorTitle: "ਡਾਕਟਰ ਕਲੀਨਿਕਲ ਸੂਟ ਅਤੇ ਓਪੀਡੀ ਟ੍ਰਾਇਜ",
  featDoctorLive: "ਪ੍ਰਮਾਣਿਤ ਡਾਕਟਰ",
  featDoctorS1Title: "ਜ਼ੀਰੋ ਡਾਟਾ ਲੀਕ ਖੋਜ ਅਤੇ OTP ਅਨਲੌਕ",
  featDoctorS1Text: "ਯੂਨਿਟ ਆਈਡੀ ਨਾਲ ਮਰੀਜ਼ ਲੱਭੋ ਜਿੱਥੇ ਸਿਰਫ ਨਾਮ ਅਤੇ ਜਨਮ ਮਿਤੀ ਦਿਖਾਈ ਦਿੰਦੀ ਹੈ ਜਦੋਂ ਤੱਕ ਮਰੀਜ਼ ਓਟੀਪੀ ਨਾ ਦੇਵੇ।",
  featDoctorS2Title: "ਵੈਦਿਆ 30 ਸਕਿੰਟ ਓਪੀਡੀ ਸੰਖੇਪ",
  featDoctorS2Text: "NAMASTE ਅਤੇ WHO ICD-11 ਕੋਡਿੰਗ ਨਾਲ ਸਿਰਫ਼ 30 ਸਕਿੰਟਾਂ ਵਿੱਚ ਮਰੀਜ਼ ਦਾ ਮੁਲਾਂਕਣ।",
  featDoctorS3Title: "ਡਾਕਟਰ ਡਾਇਰੈਕਟਰੀ ਅਤੇ ਖੇਤਰੀ ਮੈਚਿੰਗ",
  featDoctorS3Text: "ਪਹਿਲਾਂ ਸਲਾਹ ਲਏ ਗਏ ਅਤੇ ਆਪਣੇ ਖੇਤਰ ਦੇ ਡਾਕਟਰਾਂ ਨੂੰ ਤੁਰੰਤ ਲੱਭੋ।",
  featHospTitle: "ਹਸਪਤਾਲ ਐਮਰਜੈਂਸੀ ਅਤੇ ਟੱਚ ਕਿਓਸਕ",
  featHospLive: "ਐਮਰਜੈਂਸੀ ਲਈ ਤਿਆਰ",
  featHospS1Title: "ਐਮਰਜੈਂਸੀ 1-ਸਕਿੰਟ QR ਪ੍ਰੋਫਾਈਲ ਸਕੈਨਰ",
  featHospS1Text: "ਮਰੀਜ਼ ਦਾ ਕਿਊਆਰ ਸਕੈਨ ਕਰਕੇ 1 ਸਕਿੰਟ ਵਿੱਚ ਖੂਨ ਦਾ ਗਰੁੱਪ, ਐਲਰਜੀ ਅਤੇ ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ ਪ੍ਰਾਪਤ ਕਰੋ।",
  featHospS2Title: "ਪੰਜਾਬੀ ਆਵਾਜ਼ ਵਾਲਾ ਓਪੀਡੀ ਟੱਚ ਕਿਓਸਕ",
  featHospS2Text: "ਸਰੀਰ ਦੇ ਦਰਦ ਵਾਲੇ ਹਿੱਸੇ ਨੂੰ ਛੂਹ ਕੇ ਜਾਂ ਬੋਲ ਕੇ ਤੁਰੰਤ ਓਪੀਡੀ ਪਰਚੀ ਪ੍ਰਾਪਤ ਕਰੋ।",
  featHospS3Title: "ਐਂਬੂਲੈਂਸ SOS 102 ਅਤੇ ਆਡਿਟ ਲੌਗ",
  featHospS3Text: "1-ਟੈਪ ਐਮਰਜੈਂਸੀ ਕਾਲ ਅਤੇ ਹਰ ਜਾਂਚ ਦਾ ਸੁਰੱਖਿਅਤ ਡਿਜੀਟਲ ਲੌਗ।",
  access: "ਐਕਸੈੱਸ ਪੋਰਟਲ",
  choosePortal: "ਆਪਣਾ ਕੇਅਰ ਪੋਰਟਲ ਚੁਣੋ।",
  portalText: "ਹਰ ਭੂਮਿਕਾ ਲਈ ਵੱਖਰਾ ਅਨੁਭਵ, ਜਦਕਿ ਮਰੀਜ਼ ਦੀ ਮੈਡੀਕਲ ਕਹਾਣੀ ਕੇਂਦਰ ਵਿੱਚ ਰਹਿੰਦੀ ਹੈ।",
  patient: "ਮਰੀਜ਼",
  doctor: "ਡਾਕਟਰ",
  hospital: "ਹਸਪਤਾਲ",
  patientPortal: "ਮਰੀਜ਼ ਪੋਰਟਲ",
  patientPortalDesc: "ਰਿਕਾਰਡ, ਰੋਜ਼ਾਨਾ ਕੰਮ, ਦਵਾਈਆਂ ਦੀ ਅਲਮਾਰੀ ਅਤੇ ਓਟੀਪੀ ਪ੍ਰਬੰਧਨ ਕਰੋ।",
  doctorPortal: "ਡਾਕਟਰ ਪੋਰਟਲ",
  doctorPortalDesc: "ਯੂਨਿਟ ਆਈਡੀ ਨਾਲ ਮਰੀਜ਼ ਲੱਭੋ, ਰਿਕਾਰਡ ਦੇਖੋ ਅਤੇ ਵੈਦਿਆ ਓਪੀਡੀ ਕਰੋ।",
  hospitalPortal: "ਹਸਪਤਾਲ ਪੋਰਟਲ",
  hospitalPortalDesc: "ਸੰਸਥਾਗਤ ਰਿਕਾਰਡ ਤਾਲਮੇਲ, ਸਟਾਫ ਵੰਡ ਅਤੇ ਆਡਿਟ ਨਿਗਰਾਨੀ।",
  footer: "ਸੁਚੱਜੀ ਸਿਹਤ ਸੰਭਾਲ ਲਈ ਇੱਕ ਸੁਰੱਖਿਅਤ ਡਿਜੀਟਲ ਘਰ।",
  footerSub: "ਆਯੁਸ਼ਮਾਨ ਭਾਰਤ ਡਿਜੀਟਲ ਮਿਸ਼ਨ (ABDM) ਮਾਪਦੰਡਾਂ ਅਨੁਸਾਰ ਬਣਾਇਆ ਗਿਆ। ਲਾਈਵ PostgreSQL ਦੁਆਰਾ ਸੰਚਾਲਿਤ।",
  patientVaultHeader: "ਮਰੀਜ਼ ਸਿਹਤ ਵਾਲਟ",
  doctorSuiteHeader: "ਡਾਕਟਰ ਕਲੀਨਿਕਲ ਸੂਟ",
  hospitalHeader: "ਹਸਪਤਾਲ ਅਤੇ ਐਮਰਜੈਂਸੀ",
  patientSpaceTitle: "ਮਰੀਜ਼ ਸਪੇਸ",
  doctorSuiteTitle: "ਡਾਕਟਰ ਕਲੀਨਿਕਲ ਸੂਟ",
  hospitalPortalTitle: "ਹਸਪਤਾਲ ਅਤੇ ਐਮਰਜੈਂਸੀ ਪੋਰਟਲ",
  dashboard: "ਡੈਸ਼ਬੋਰਡ",
  profilePage: "ਮੇਰਾ ਪ੍ਰੋਫਾਈਲ ਅਤੇ QR",
  recordsPage: "ਮੈਡੀਕਲ ਰਿਕਾਰਡ",
  uploadPage: "ਡਾਕੂਮੈਂਟ ਅੱਪਲੋਡ",
  todoPage: "ਦਵਾਈ ਰੁਟੀਨ",
  timelinePage: "ਸਿਹਤ ਟਾਈਮਲਾਈਨ",
  inventoryPage: "ਦਵਾਈ ਕੈਬਿਨੇਟ",
  aiCompanionPage: "ਮੇਡੀ-ਏਆਈ ਸਾਥੀ",
  vaidyaPage: "ਵੈਦਿਆ 30 ਸਕਿੰਟ ਚਾਰਟ",
  delegationPage: "ਸਹਿਮਤੀ ਅਤੇ ਐਕਸੈੱਸ",
  kioskPage: "ਓਪੀਡੀ ਟੱਚ ਕਿਓਸਕ",
  scannerPage: "ਐਮਰਜੈਂਸੀ QR ਸਕੈਨਰ",
};

T.kn = {
  ...base,
  unitId: "ಯುನಿಟ್ ID",
  newHere: "MediLocker ಗೆ ಹೊಸಬರೇ?",
  signUp: "ಖಾತೆ ರಚಿಸಿ →",
  navFeatures: "ವೈಶಿಷ್ಟ್ಯಗಳು",
  navHowItWorks: "ಕೆಲಸ ಮಾಡುವ ವಿಧಾನ",
  navSecurity: "ಕ್ಲಿನಿಕಲ್ ಸುರಕ್ಷತೆ",
  navPortals: "ಪೋರ್ಟಲ್‌ಗಳು",
  setLocation: "ಸ್ಥಳ ಹೊಂದಿಸಿ",
  signIn: "ಸೈನ್ ಇನ್ ↗",
  signOut: "ಸೈನ್ ಔಟ್",
  eyebrow: "ಆರೋಗ್ಯ ನಿರ್ವಹಣೆಯ ಸುಲಭ ಮತ್ತು ಸುರಕ್ಷಿತ ಮಾರ್ಗ",
  hero1: "ನಿಮ್ಮ ಆರೋಗ್ಯ ಕಥೆ,",
  hero2: "ಒಂದೇ ಸುರಕ್ಷಿತ ಸ್ಥಳದಲ್ಲಿ.",
  heroText: "MediLocker ರೋಗಿಯ ದಾಖಲೆಗಳು, ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್‌ಗಳು, ವರದಿಗಳು ಮತ್ತು ಔಷಧಿ ದಿನಚರಿಯನ್ನು ಸುಂದರವಾಗಿ ವ್ಯವಸ್ಥಿತ ಡಿಜಿಟಲ್ ಅನುಭವಕ್ಕೆ ತರುತ್ತದೆ.",
  enter: "MediLocker ಪ್ರವೇಶಿಸಿ ↗",
  seeHow: "ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ ನೋಡಿ ↓",
  sosHero: "ತುರ್ತು SOS 102",
  designed: "ರೋಗಿಯನ್ನು ಕೇಂದ್ರವಾಗಿಟ್ಟುಕೊಂಡ ವಿನ್ಯಾಸ",
  records: "ಮೊದಲ ಭೇಟಿಯಿಂದ ಮುಂದಿನ ಚಿಕಿತ್ಸೆಯವರೆಗೆ ಎಲ್ಲಾ ದಾಖಲೆಗಳು ಸುರಕ್ಷಿತವಾಗಿರುತ್ತವೆ.",
  overview: "ಆರೋಗ್ಯ ಅವಲೋಕನ",
  secured: "ಸುರಕ್ಷಿತ",
  goodMorning: "ಶುಭೋದಯ",
  profile: "ಪ್ರೊಫೈಲ್ ಪೂರ್ಣತೆ",
  keepUpdated: "ನಿಮ್ಮ ವೈದ್ಯಕೀಯ ಮಾಹಿತಿಯನ್ನು ನವೀಕರಿಸಿ ಇಟ್ಟುಕೊಳ್ಳಿ.",
  medicalRecords: "ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳು",
  activeMeds: "ಸಕ್ರಿಯ ಔಷಧಿಗಳು",
  nextMedication: "ಮುಂದಿನ ಔಷಧಿ",
  afterLunch: "ಮಧ್ಯಾಹ್ನದ ಊಟದ ನಂತರ · 1:30",
  workspaceTitle: "ಏಕೀಕೃತ ಸಾರ್ವಭೌಮ ಆರೋಗ್ಯ ಕಾರ್ಯಕ್ಷೇತ್ರ",
  trust1Title: "100% ರೋಗಿಯ ಸಂಪೂರ್ಣ ನಿಯಂತ್ರಣ",
  trust1Desc: "1-ಕ್ಲಿಕ್‌ನಲ್ಲಿ ತಕ್ಷಣದ ಪ್ರವೇಶ ರದ್ದತಿ",
  trust2Title: "ACID ಡೇಟಾಬೇಸ್ ಎಂಜಿನ್",
  trust2Desc: "ಎಂಟರ್‌ಪ್ರೈಸ್ PostgreSQL ಸಂಗ್ರಹಣೆ",
  trust3Title: "15-ನಿಮಿಷದ ಡೈನಾಮಿಕ್ OTP",
  trust3Desc: "ವೈದ್ಯಕೀಯ ಪ್ರವೇಶಕ್ಕಾಗಿ 6-ಅಂಕಿಯ ಕೋಡ್",
  trust4Title: "ಶೂನ್ಯ ಡೇಟಾ ಸೋರಿಕೆ ಹುಡುಕಾಟ",
  trust4Desc: "ಹುಡುಕಾಟದಲ್ಲಿ ಹೆಸರು ಮತ್ತು ಜನ್ಮದಿನಾಂಕ ಮಾತ್ರ ಗೋಚರ",
  featuresEyebrow: "ಸಾರ್ವಭೌಮ ಆರೋಗ್ಯ ವಾಸ್ತುಶಿಲ್ಪ",
  featuresTitle: "ಸಂಪೂರ್ಣ ಕ್ಲಿನಿಕಲ್ ಮುಂದುವರಿಕೆಗಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ.",
  featuresSubtitle: "ರೋಗಿಗಳು, ವೈದ್ಯರು ಮತ್ತು ತುರ್ತು ಆಸ್ಪತ್ರೆ ಜಾಲವನ್ನು ನೈಜ ಸಮಯದಲ್ಲಿ ಜೋಡಿಸುವ ಡಿಜಿಟಲ್ ವೇದಿಕೆ.",
  featVaultTitle: "ಆರೋಗ್ಯ ವಾಲ್ಟ್ ಮತ್ತು ನಿರಂತರ ಆರೈಕೆ",
  featVaultLive: "ಲೈವ್ ಮತ್ತು ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲಾಗಿದೆ",
  featVaultS1Title: "ಸಮಾಲೋಚನೆ ದಿನಾಂಕ ಮತ್ತು ಔಷಧಿ ಟ್ರ್ಯಾಕಿಂಗ್",
  featVaultS1Text: "ದಿನಾಂಕದೊಂದಿಗೆ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಉಳಿಸಿ. ಚಾಲ್ತಿಯಲ್ಲಿರುವ ಔಷಧಿಗಳು ಸಕ್ರಿಯವಾಗಿರುತ್ತವೆ ಮತ್ತು ಮುಗಿದ ಕೋರ್ಸ್‌ಗಳು ಆರ್ಕೈವ್ ಆಗುತ್ತವೆ.",
  featVaultS2Title: "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಮತ್ತು ಲ್ಯಾಬ್ ವರದಿ ವೀಕ್ಷಕ",
  featVaultS2Text: "ಡೇಟಾ ಸೋರಿಕೆಯಿಲ್ಲದೆ ಸುರಕ್ಷಿತ ಇನ್‌ಲೈನ್ ವೀಕ್ಷಕದೊಂದಿಗೆ ದಾಖಲೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ.",
  featVaultS3Title: "ಮಧ್ಯರಾತ್ರಿ 12 ಕ್ಕೆ ರೀಸೆಟ್ ಮತ್ತು 2 ದಿನ ಮುಂಚಿತ ರಿಫಿಲ್ ಎಚ್ಚರಿಕೆ",
  featVaultS3Text: "ಬೆಳಗ್ಗೆ, ಮಧ್ಯಾಹ್ನ ಮತ್ತು ರಾತ್ರಿಯ ಔಷಧಿ ಪಟ್ಟಿ ಮಧ್ಯರಾತ್ರಿ ರೀಸೆಟ್ ಆಗುತ್ತದೆ ಹಾಗೂ ಔಷಧಿ ಮುಗಿಯುವ 2 ದಿನ ಮುಂಚಿತವಾಗಿ ಎಚ್ಚರಿಕೆ ಸಿಗುತ್ತದೆ.",
  featDoctorTitle: "ವೈದ್ಯರ ಕ್ಲಿನಿಕಲ್ ಸೂಟ್ ಮತ್ತು ತ್ವರಿತ ಟ್ರಯಾಜ್",
  featDoctorLive: "ಪರಿಶೀಲಿಸಿದ ವೈದ್ಯರು",
  featDoctorS1Title: "ಶೂನ್ಯ ಡೇಟಾ ಸೋರಿಕೆ ಹುಡುಕಾಟ ಮತ್ತು OTP ಅನ್‌ಲಾಕ್",
  featDoctorS1Text: "ಯೂನಿಟ್ ಐಡಿ ಮೂಲಕ ಹುಡುಕಿದಾಗ ಹೆಸರು ಮತ್ತು ಜನ್ಮದಿನಾಂಕ ಮಾತ್ರ ಕಾಣಿಸುತ್ತದೆ, ಪೂರ್ಣ ದಾಖಲೆಗಳಿಗೆ ರೋಗಿಯ 6-ಅಂಕಿಯ ಒಟಿಪಿ ಅಗತ್ಯ.",
  featDoctorS2Title: "ವೈದ್ಯ 30 ಸೆಕೆಂಡ್ ಒಪಿಡಿ ಸಾರಾಂಶ",
  featDoctorS2Text: "NAMASTE ಮತ್ತು WHO ICD-11 ಮಾನದಂಡಗಳೊಂದಿಗೆ ಕೇವಲ 30 ಸೆಕೆಂಡುಗಳಲ್ಲಿ ರೋಗಿಯ ವಿವರವಾದ ಚಾರ್ಟ್ ಸಾರಾಂಶ.",
  featDoctorS3Title: "ಸ್ಥಳೀಯ ವೈದ್ಯರ ಡೈರೆಕ್ಟರಿ",
  featDoctorS3Text: "ಹಿಂದೆ ಸಂಪರ್ಕಿಸಿದ ಮತ್ತು ನಿಮ್ಮ ಪ್ರದೇಶದ ತಜ್ಞ ವೈದ್ಯರನ್ನು ಸುಲಭವಾಗಿ ಹುಡುಕಿ.",
  featHospTitle: "ಆಸ್ಪತ್ರೆ ತುರ್ತುಸ್ಥಿತಿ ಮತ್ತು ಟಚ್ ಕಿಯೋಸ್ಕ್",
  featHospLive: "ತುರ್ತು ಸೇವೆಗೆ ಸದಾ ಸಿದ್ಧ",
  featHospS1Title: "ತುರ್ತು 1-ಸೆಕೆಂಡ್ QR ಪ್ರೊಫೈಲ್ ಸ್ಕ್ಯಾನರ್",
  featHospS1Text: "ರೋಗಿಯ ಕ್ಯೂಆರ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ 1 ಸೆಕೆಂಡಿನಲ್ಲಿ ರಕ್ತದ ಗುಂಪು, ಅಲರ್ಜಿ ಮತ್ತು ತುರ್ತು ಸಂಪರ್ಕ ವಿವರ ಪಡೆಯಿರಿ.",
  featHospS2Title: "ಕನ್ನಡ ಧ್ವನಿ ಮಾರ್ಗದರ್ಶನವಿರುವ ಟಚ್ ಕಿಯೋಸ್ಕ್",
  featHospS2Text: "ದೇಹದ ನೋವಿರುವ ಭಾಗವನ್ನು ಮುಟ್ಟಿ ಅಥವಾ ಧ್ವನಿ ಮೂಲಕ ತಕ್ಷಣ ಒಪಿಡಿ ಟಿಕೆಟ್ ಪಡೆಯಿರಿ.",
  featHospS3Title: "ಆಂಬ್ಯುಲೆನ್ಸ್ SOS 102 ಮತ್ತು ಆಡಿಟ್ ಲಾಗ್",
  featHospS3Text: "1-ಟ್ಯಾಪ್ ತುರ್ತು ಕರೆ ಮತ್ತು ದಾಖಲೆ ಪ್ರವೇಶದ ಸುರಕ್ಷಿತ ಡಿಜಿಟಲ್ ಲಾಗ್.",
  access: "ಪ್ರವೇಶ ಪೋರ್ಟಲ್‌ಗಳು",
  choosePortal: "ನಿಮ್ಮ ಕೇರ್ ಪೋರ್ಟಲ್ ಆಯ್ಕೆಮಾಡಿ.",
  portalText: "ಪ್ರತಿ ಪಾತ್ರಕ್ಕೂ ಕೇಂದ್ರೀಕೃತ ಅನುಭವ, ರೋಗಿಯ ವೈದ್ಯಕೀಯ ಕಥೆ ಕೇಂದ್ರದಲ್ಲಿರುತ್ತದೆ.",
  patient: "ರೋಗಿ",
  doctor: "ವೈದ್ಯರು",
  hospital: "ಆಸ್ಪತ್ರೆ",
  patientPortal: "ರೋಗಿ ಪೋರ್ಟಲ್",
  patientPortalDesc: "ದಾಖಲೆಗಳು, ದಿನಚರಿ, ಔಷಧಿ ಕ್ಯಾಬಿನೆಟ್ ಮತ್ತು ಒಟಿಪಿ ನಿಯೋಗಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
  doctorPortal: "ವೈದ್ಯರ ಪೋರ್ಟಲ್",
  doctorPortalDesc: "ಯುನಿಟ್ ಐಡಿ ಮೂಲಕ ರೋಗಿಗಳನ್ನು ಹುಡುಕಿ ಮತ್ತು ವೈದ್ಯ ಒಪಿಡಿ ನಿರ್ವಹಿಸಿ.",
  hospitalPortal: "ಆಸ್ಪತ್ರೆ ಪೋರ್ಟಲ್",
  hospitalPortalDesc: "ಸಂಸ್ಥೆಯ ದಾಖಲೆಗಳ ಸಮನ್ವಯ, ಸಿಬ್ಬಂದಿ ಹಂಚಿಕೆ ಮತ್ತು ಆಡಿಟ್ ಮೇಲ್ವಿಚಾರಣೆ.",
  footer: "ವ್ಯವಸ್ಥಿತ ಆರೋಗ್ಯ ರಕ್ಷಣೆಗಾಗಿ ಒಂದು ಸುರಕ್ಷಿತ ಡಿಜಿಟಲ್ ತಾಣ.",
  footerSub: "ಆಯುಷ್ಮಾನ್ ಭಾರತ್ ಡಿಜಿಟಲ್ ಮಿಷನ್ (ABDM) ಮಾನದಂಡಗಳ ಅನ್ವಯ ವಿನ್ಯಾಸ. ಲೈವ್ PostgreSQL ನಿಂದ ಬೆಂಬಲಿತವಾಗಿದೆ.",
  patientVaultHeader: "ರೋಗಿ ಆರೋಗ್ಯ ವಾಲ್ಟ್",
  doctorSuiteHeader: "ವೈದ್ಯ ಕ್ಲಿನಿಕಲ್ ಸೂಟ್",
  hospitalHeader: "ಆಸ್ಪತ್ರೆ ಮತ್ತು ತುರ್ತು",
  patientSpaceTitle: "ರೋಗಿ ಸಾರ್ವಭೌಮ ಸ್ಪೇಸ್",
  doctorSuiteTitle: "ವೈದ್ಯ ಕ್ಲಿನಿಕಲ್ ಸೂಟ್",
  hospitalPortalTitle: "ಆಸ್ಪತ್ರೆ ಮತ್ತು ತುರ್ತು ಪೋರ್ಟಲ್",
  dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
  profilePage: "ನನ್ನ ಪ್ರೊಫೈಲ್ ಮತ್ತು QR",
  recordsPage: "ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳು",
  uploadPage: "ಡಾಕ್ಯುಮೆಂಟ್ ಅಪ್ಲೋಡ್",
  todoPage: "ಔಷಧಿ ದಿನಚರಿ",
  timelinePage: "ಆರೋಗ್ಯ ಟೈಮ್‌ಲೈನ್",
  inventoryPage: "ಔಷಧಿ ಕ್ಯಾಬಿನೆಟ್",
  aiCompanionPage: "ಮೆಡಿ-AI ಸಹಾಯಕ",
  vaidyaPage: "ವೈದ್ಯ 30 ಸೆ. ಚಾರ್ಟ್",
  delegationPage: "ಸಮ್ಮತಿ ಮತ್ತು ಪ್ರವೇಶ",
  kioskPage: "ಒಪಿಡಿ ಟಚ್ ಕಿಯೋಸ್ಕ್",
  scannerPage: "ತುರ್ತು QR ಸ್ಕ್ಯಾನರ್",
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    try {
      return localStorage.getItem('medilockerLanguage') || 'en';
    } catch (e) {
      return 'en';
    }
  });

  const setLanguage = (lang) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('medilockerLanguage', lang);
    } catch (e) {}
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ur' ? 'rtl' : 'ltr';
  };

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ur' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key, fallback = '') => {
    const dict = T[language] || T.en;
    if (dict && dict[key]) return dict[key];
    if (T.en && T.en[key]) return T.en[key];
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir: language === 'ur' ? 'rtl' : 'ltr' }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      language: 'en',
      setLanguage: () => {},
      t: (k, fb = '') => fb || k,
      dir: 'ltr'
    };
  }
  return context;
}
